server:
  port: 8080
spring:
  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    encoding: UTF-8
    excluded-view-names:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html